import type { AgentPlugin } from '../index'
import type {
  AgentPhaseEvent,
  AgentRunState,
  JsonLike
} from '@nanoagent/kernel'
import type { ModelMessage } from 'ai'
import { Effect } from 'effect'

// Equivalent to Codex's TokenUsageInfo / TotalTokenUsageBreakdown
export type TokenUsageInfo = {
  readonly lastApiResponseTotalTokens: number
  readonly allHistoryItemsModelVisibleBytes: number
  readonly estimatedTokensSinceLastResponse: number
}

// Equivalent to Codex's RateLimitSnapshot
export type RateLimitSnapshot = {
  readonly limitId?: string
  readonly credits?: number
  readonly planType?: string
}

// Equivalent to Codex's ContextManager
export type ContextManager = {
  // ModelMessage is cast to any/JsonLike for storage
  readonly items: readonly JsonLike[]
  readonly historyVersion: number
  readonly tokenInfo?: TokenUsageInfo
  readonly referenceContextItem?: JsonLike
}

// Equivalent to Codex's SessionState
export type SessionContext = {
  readonly sessionConfiguration?: JsonLike
  readonly history: ContextManager
  readonly latestRateLimits?: RateLimitSnapshot
  readonly serverReasoningIncluded: boolean
  readonly dependencyEnv: { readonly [key: string]: string }
  readonly mcpDependencyPrompted: readonly string[]
  readonly activeConnectorSelection: readonly string[]
  readonly grantedPermissions?: JsonLike
  readonly nextTurnIsFirst: boolean
}

type SessionPersister = (args: {
  state: AgentRunState<SessionContext>
  events: AgentPhaseEvent[]
}) => Promise<void>

export type SessionPluginOptions = {
  persister?: SessionPersister
}

/**
 * sessionPlugin implements the core session logic mirroring Codex's SessionState.
 * It manages the conversation history, token estimates, rate limits, and durable persistence.
 */
export function sessionPlugin(
  options?: SessionPluginOptions
): AgentPlugin<SessionContext> {
  return {
    name: 'session',

    // The session plugin provides hooks to project the history into the prompt
    // and record results after the model completes.
    hooks: {
      onRunStarted: async ({ context }) => {
        // Initialize the session context if it doesn't exist yet
        if (!context.history) {
          return {
            context: {
              ...(context as SessionContext),
              history: {
                items: [],
                historyVersion: 0
              },
              serverReasoningIncluded: false,
              dependencyEnv: {},
              mcpDependencyPrompted: [],
              activeConnectorSelection: [],
              nextTurnIsFirst: true
            } as SessionContext
          }
        }
      },

      onTurnPrepared: async ({ context, turn }) => {
        // Here we project the session history into the model's message array,
        // mirroring ContextManager::for_prompt

        const messages = [...(context.history?.items ?? [])] as ModelMessage[]

        return {
          value: {
            ...turn.modelArgs,
            model: turn.modelArgs?.model ?? 'openai/gpt-4o',
            messages: messages as any // cast required for Vercel AI SDK types vs AgentTurnPreparedValue
          } as any
        }
      },

      onTurnCompleted: async ({ context, turn }) => {
        const result = turn.modelResult
        if (!result) return {}

        // Mirroring ContextManager::record_items
        // We append the new messages generated by the model/tool calls in this turn.
        const newItems = [...(context.history?.items ?? [])] as JsonLike[]

        // Add the assistant's response
        newItems.push(...(result.response.messages as unknown as JsonLike[]))

        // Calculate token usage mirroring ContextManager::update_token_info
        const usage = result.totalUsage
        const tokenInfo: TokenUsageInfo = {
          lastApiResponseTotalTokens: usage?.totalTokens ?? 0,
          allHistoryItemsModelVisibleBytes: 0, // Would be calculated based on payload bytes
          estimatedTokensSinceLastResponse: 0
        }

        return {
          context: {
            ...context,
            nextTurnIsFirst: false,
            history: {
              ...context.history,
              items: newItems,
              historyVersion: (context.history?.historyVersion ?? 0) + 1,
              tokenInfo
            }
          } as SessionContext
        }
      }
    },

    // Handle durable persistence if a persister is provided. This maps to the
    // transactional barrier in Codex where State and Events are written together.
    ...(options?.persister && {
      saveState: args => {
        return Effect.tryPromise(() => options.persister!(args as any))
      }
    })
  }
}
